apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-directory
  namespace: hr-dev
  labels:
    app: employee-directory
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-directory
  template:
    metadata:
      labels:
        app: employee-directory
        type: backend
    spec:
      containers:
        - name: employee-directory
          image: davidmacdonaldkong/employees-directory:5ad1232764abd925cbe025a3d2179e55f63db5a2
          readinessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          ports:
            - containerPort: 8080
