apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-directory
  namespace: hr-dev
  labels:
    app: employee-directory
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-directory
  template:
    metadata:
      labels:
        app: employee-directory
        type: backend
    spec:
      containers:
        - name: employee-directory
          image: davidmacdonaldkong/employees-directory:bae124965e5edf7e738b70b16c6b33b2e0b8edfa
          readinessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          ports:
            - containerPort: 8080
