apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-directory
  namespace: hr-dev
  labels:
    app: employee-directory
    type: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employee-directory
  template:
    metadata:
      labels:
        app: employee-directory
        type: backend
    spec:
      containers:
        - name: employee-directory
          image: davidmacdonaldkong/employees-directory:61e11c37d91a382926b3ab18d3c48bf873aa48b6
          readinessProbe:
            httpGet:
              path: /api/employees
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          ports:
            - containerPort: 8080
